### PR TITLE
Validation & upload developer experience (#20, #21, #37, #40)

### LINKED ISSUE #20: Web Annotator requires lab_id but documentation does not stress this
**Describe the bug**
The web annotator currently reads the lab id from the contributor config, but the documentation does not clarify this, and the error message does not tell a user what to do.

**To Reproduce**
1. Delete or move contributor config
2. Launch web annotator

**Expected behavior**
The error message should clearly outline how to obtain a lab id and where the lab id needs to be placed

Reported by @JMaria88

### LINKED ISSUE #21: Better error messaging in verify and upload
When verifying and uploading a dataset, there are error messages that can occur during validation. One example is " action_joint_names count does not match actions/joint_position DOF: expected 12, got 14", same for observation space. There are likely others. 

This is confusing for the user. If you are not too familiar with oopsie-tools details, it's unclear how to fix and proceed from here.

Better error messages explaining what the issue is and where it could be coming from, would help.

### LINKED ISSUE #37: [Suggestion] Confirmation of uploaded data
**Is your feature request related to a problem? Please describe.**
Currently there is very little feedback to users about whether their data got uploaded correctly. Since we can't run stats 24/7, it would be great to give the labs scripts with which they can very quickly query their own repository.

### LINKED ISSUE #40: [Suggestion] Warn users about low diversity
**Is your feature request related to a problem? Please describe.**
When users upload data, we want to flag low task and annotation diversity to them. This will need to be fine-tuned to the requirements for contribution, but a small nudge on the user end might help to a) catch unintentional copied annotations and b) alert inattentive annotators.

### PR DESCRIPTION
**Pull request by renwang435**
> Backend-only, branched off `main` — **independent of the annotator UI stack (#41–#45)**, so it
> can be reviewed/merged in parallel.

## Summary

Developer-experience fixes for the validate → upload pipeline.

- **#20 — `lab_id` errors.** New `oopsie_tools/utils/contributor_config.read_contributor_config`
  reads the config None-safely and raises **one clear, actionable error** (with the registration
  hint) when `lab_id` is blank (`lab_id:`), missing, or still the placeholder — instead of the
  cryptic `'NoneType' object has no attribute 'strip'` crash. Used by `EpisodeRecorder` and
  `upload.py`, and read **lazily** (only when uploading) so validation / `--skip_upload` / `--help`
  work on a fresh checkout. A conftest fixture supplies a test lab_id so **the test suite runs green
  on a fresh checkout** (previously 40 tests failed on the empty committed config). AI_CONTEXT note added.
- **#21 — clearer validation errors.** `validate_h5_file` now accepts `log_path` (fixes a
  `TypeError` on the single-episode upload path); fixed a latent `KeyError` that masked the
  "missing observations key" message; and reworded the DOF/joint-name mismatch messages to name
  both sides ("the profile lists N … but the recorded array has M DOF …").
- **#37 — upload confirmation + repo stats.** After upload the repo is listed back to confirm the
  episode count (with a mismatch warning); new `scripts/validate_and_upload/query_submissions.py`
  lets a lab query its own `OopsieData-Submissions/<lab_id>` repo for counts anytime. `hf_login`
  now runs only when actually uploading, and the documented `HF_TOKEN` env override is honored.
- **#40 — low-diversity warning.** New `check_diversity` (attrs-only, never raises) warns at upload
  time about single-instruction datasets or copy-pasted failure descriptions; `--strict-diversity`
  turns warnings into a non-zero exit.

## ⚠️ One behavior note
`--skip_upload` (and `--help`) now work **without** a filled-in contributor config, and `hf_login`
only happens when uploading — so contributors can validate their data offline before registering.

## How to verify

```bash
# #20: a blank lab_id gives a clear message (not None.strip); the suite is green on a fresh checkout
uv run pytest oopsie_tools/test/          # green apart from one sandbox-only path-permission test

# #21 + #40: validate offline (no HF auth needed) and see diversity warnings
uv run python scripts/validate_and_upload/upload.py --path <samples-dir> --skip_upload
uv run python scripts/validate_and_upload/upload.py --path <samples-dir> --episode_id 000001 --skip_upload   # no TypeError
uv run python scripts/validate_and_upload/upload.py --path <samples-dir> --skip_upload --strict-diversity     # non-zero exit if low diversity

# #37: query your lab's submissions repo (needs your real lab_id + token in configs/contributor_config.yaml)
uv run python scripts/validate_and_upload/query_submissions.py
```
- **#20:** with `lab_id:` blank in `configs/contributor_config.yaml`, `upload.py … --skip_upload`
  validates fine; only an actual upload asks for a real lab_id, and then the error (if unset) points
  to the registration form.
- **#21:** a robot profile whose `robot_state_joint_names`/`action_joint_names` count doesn't match
  the recorded DOF prints an explanatory message; single-episode validation + `--log-path` works and
  writes a non-empty log.
- **#40:** a folder of episodes with one repeated instruction / identical failure descriptions emits
  `[diversity]` warnings.

Closes #20
Closes #21
Closes #37
Closes #40

### CODE REVIEW

**Review by cvoelcker — DISMISSED** [review]
lgtm
